find_package(Doxygen)
if (DOXYGEN_FOUND)
# doxygen_add_docs()
  set(INPUT_FILES src/ app/)
  set(DOXYGEN_RECURSIVE YES)
  set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/docs)
  set(DOXYGEN_GENERATE_HTML YES)
  set(DOXYGEN_GENERATE_MAN YES)
  set(DOXYGEN_MARKDOWN_SUPPORT YES)
  set(DOXYGEN_AUTOLINK_SUPPORT YES)
  set(DOXYGEN_HAVE_DOT YES)
  set(DOXYGEN_COLLABORATION_GRAPH YES)
  set(DOXYGEN_CLASS_GRAPH YES)
  set(DOXYGEN_UML_LOOK YES)
  set(DOXYGEN_DOT_UML_DETAILS YES)
  set(DOXYGEN_DOT_WRAP_THRESHOLD 100)
  set(DOXYGEN_CALL_GRAPH YES)
  set(DOXYGEN_QUIET YES)
  # set(DOXYGEN_FILE_PATTERNS "*.cpp *.hpp *.c *.h")
  # add_custom_target(docs ALL ${DOXYGEN_EXECUTABLE} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/docs COMMENT "Generate documentation")
  doxygen_add_docs(docs ${INPUT_FILES} ALL COMMENT "Generate documentation")
else()
  message(WARNING "Doxygen not found, not building docs")
endif()
