function(add_sanitizer_flags)
if(NOT ${ENABLE_SANITIER_ADDR} AND NOT ${ENABLE_SANITIZE_UNDEF})
  message(STATUS "Sanitizers deactivated")
  return()
endif()
if(CMAKE_CXX_COMPILER_ID MATCHES "CLANG" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
# -fno-omit-frame-pointer 是一个 GCC 和 Clang 编译器的选项，用于控制函数的帧指针（frame pointer）行为。
# 具体来说，这个选项会禁止编译器在生成代码时省略帧指针
  add_compile_options("-fno-omit-frame-pointer")
  add_link_options("-fno-omit-frame-pointer")
if(${ENABLE_SANITIZE_ADDR})
  add_compile_options("-fsanitize=address")
  add_link_options("-fsanitize=address")
endif()
if(${ENABLE_SANITIZE_UNDEF})
  add_compile_options("-fsanitize=undefined")
  add_link_options("-fsanitize=undefined")
endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
if(${ENABLE_SANITIZE_ADDR})
  add_compile_options("/fsanitize=address")
endif()
if(${ENABLE_SANITIZE_UNDEF})
  message(STATUS "Undefined sanitizers are not supported by MSVC")
endif()
else()
    message(STATUS "Sanitizers are not supported by this compiler")
endif()
endfunction()
